#ifndef CTJSON5__JSON5__HPP
#define CTJSON5__JSON5__HPP

// THIS FILE WAS GENERATED BY TABLEWRIGHT TOOL, DO NOT MODIFY THIS FILE

#include "../ctll/grammars.hpp"

namespace ctjson5 {

struct json5 {

	// NONTERMINALS:
	struct after_zero {};
	struct array_after_comma {};
	struct array_content {};
	struct array_tail {};
	struct block_comment {};
	struct block_comment_star {};
	struct comment {};
	struct continuation_lf {};
	struct document {}; using _start = document;
	struct dq_content {};
	struct escape {};
	struct exp_first {};
	struct exp_part {};
	struct exp_sign {};
	struct exp_tail {};
	struct frac_part {};
	struct frac_tail {};
	struct hex_tail {};
	struct identifier_tail {};
	struct int_tail {};
	struct leading_frac {};
	struct line_comment {};
	struct member {};
	struct number {};
	struct object_after_comma {};
	struct object_content {};
	struct object_tail {};
	struct signed_numeric {};
	struct sq_content {};
	struct value {};
	struct ws {};

	// 'action' types:
	struct begin_array: ctll::action {};
	struct begin_hex: ctll::action {};
	struct begin_number: ctll::action {};
	struct begin_object: ctll::action {};
	struct begin_string: ctll::action {};
	struct end_array: ctll::action {};
	struct end_hex: ctll::action {};
	struct end_object: ctll::action {};
	struct end_string: ctll::action {};
	struct finish_infinity: ctll::action {};
	struct finish_nan: ctll::action {};
	struct line_continuation: ctll::action {};
	struct make_key: ctll::action {};
	struct make_member: ctll::action {};
	struct push_escaped_char: ctll::action {};
	struct push_false: ctll::action {};
	struct push_hex: ctll::action {};
	struct push_null: ctll::action {};
	struct push_number_char: ctll::action {};
	struct push_string_char: ctll::action {};
	struct push_true: ctll::action {};

	// TERMINALS
	using set_1 = ctll::set<'\x09','\x0A','\x0B','\x0C','\x0D',' ','\"','\'','+','-','.','/','0','1','2','3','4','5','6','7','8','9','I','N','[','f','n','t','\x7B',U'\xC2',U'\xE2',U'\xEF'>;
	using xa0 = ctll::term<U'\xA0'>;
	using xbb = ctll::term<U'\xBB'>;
	using xbf = ctll::term<U'\xBF'>;
	using x80 = ctll::term<U'\x80'>;
	using ls_ps_third = ctll::set<U'\xA8',U'\xA9'>;
	using ws_char = ctll::set<'\x09','\x0A','\x0B','\x0C','\x0D',' '>;
	using set_2 = ctll::set<'\"','$','\'','+',',','-','.','0','1','2','3','4','5','6','7','8','9',':','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[',']','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','\x7B','\x7D'>;
	using slash = ctll::term<'/'>;
	using Â = ctll::term<U'\xC2'>;
	using ï = ctll::term<U'\xEF'>;
	using â = ctll::term<U'\xE2'>;
	using star = ctll::term<'*'>;
	using line_comment_chars = ctll::neg_set<'\x0A','\x0D'>;
	using line_comment_chars2 = ctll::set<'\x0A','\x0D'>;
	using block_comment_chars = ctll::neg_set<'*'>;
	using r = ctll::term<'r'>;
	using u = ctll::term<'u'>;
	using e = ctll::term<'e'>;
	using a = ctll::term<'a'>;
	using l = ctll::term<'l'>;
	using s = ctll::term<'s'>;
	using lbrace = ctll::term<'\x7B'>;
	using lbracket = ctll::term<'['>;
	using quote = ctll::term<'\"'>;
	using squote = ctll::term<'\''>;
	using plus__minus__dot__digit__I__N = ctll::set<'+','-','.','0','1','2','3','4','5','6','7','8','9','I','N'>;
	using t = ctll::term<'t'>;
	using f = ctll::term<'f'>;
	using n = ctll::term<'n'>;
	using rbrace = ctll::term<'\x7D'>;
	using doublequote__id_start__quote = ctll::set<'\"','$','\'','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using comma = ctll::term<','>;
	using colon = ctll::term<':'>;
	using id_start = ctll::set<'$','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using id_continue = ctll::set<'$','0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using ws_char__slash__colon__Â__â__ï = ctll::set<'\x09','\x0A','\x0B','\x0C','\x0D',' ','/',':',U'\xC2',U'\xE2',U'\xEF'>;
	using rbracket = ctll::term<']'>;
	using set_3 = ctll::set<'\"','\'','+','-','.','0','1','2','3','4','5','6','7','8','9','I','N','[','f','n','t','\x7B'>;
	using dq_chars = ctll::neg_set<'\x0A','\x0D','\"','\\'>;
	using backslash = ctll::term<'\\'>;
	using sq_chars = ctll::neg_set<'\x0A','\x0D','\'','\\'>;
	using hexdig = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','a','b','c','d','e','f'>;
	using escapable__d0 = ctll::set<'\"','\'','/','0','\\','b','f','n','r','t','v'>;
	using x_char = ctll::set<'X','x'>;
	using x0a = ctll::term<'\x0A'>;
	using x0d = ctll::term<'\x0D'>;
	using self_escape_chars = ctll::neg_set<'\x0A','\x0D','\"','\'','/','0','1','2','3','4','5','6','7','8','9','X','\\','b','f','n','r','t','u','v','x',U'\xE2'>;
	using doublequote__quote__backslash = ctll::set<'\"','\'','\\'>;
	using i = ctll::term<'i'>;
	using y = ctll::term<'y'>;
	using N = ctll::term<'N'>;
	using minus = ctll::term<'-'>;
	using plus = ctll::term<'+'>;
	using zero = ctll::term<'0'>;
	using onenine = ctll::set<'1','2','3','4','5','6','7','8','9'>;
	using dot = ctll::term<'.'>;
	using I = ctll::term<'I'>;
	using ws_char__comma__dot__slash__e_char__sclose__cclose__Â__â__ï = ctll::set<'\x09','\x0A','\x0B','\x0C','\x0D',' ',',','.','/','E',']','e','\x7D',U'\xC2',U'\xE2',U'\xEF'>;
	using ws_char__comma__slash__sclose__cclose__Â__â__ï = ctll::set<'\x09','\x0A','\x0B','\x0C','\x0D',' ',',','/',']','\x7D',U'\xC2',U'\xE2',U'\xEF'>;
	using digit = ctll::set<'0','1','2','3','4','5','6','7','8','9'>;
	using ws_char__comma__slash__e_char__sclose__cclose__Â__â__ï = ctll::set<'\x09','\x0A','\x0B','\x0C','\x0D',' ',',','/','E',']','e','\x7D',U'\xC2',U'\xE2',U'\xEF'>;
	using e_char = ctll::set<'E','e'>;
	using plus__minus = ctll::set<'+','-'>;

	// (q)LL1 function:
	static constexpr auto rule(document, set_1) -> ctll::push<ws, value, ws>;

	static constexpr auto rule(ws, ws_char) -> ctll::push<ctll::anything, ws>;
	static constexpr auto rule(ws, set_2) -> ctll::epsilon;
	static constexpr auto rule(ws, ctll::epsilon) -> ctll::epsilon;
	static constexpr auto rule(ws, slash) -> ctll::push<ctll::anything, comment, ws>;
	static constexpr auto rule(ws, Â) -> ctll::push<ctll::anything, xa0, ws>;
	static constexpr auto rule(ws, ï) -> ctll::push<ctll::anything, xbb, xbf, ws>;
	static constexpr auto rule(ws, â) -> ctll::push<ctll::anything, x80, ls_ps_third, ws>;

	static constexpr auto rule(comment, slash) -> ctll::push<ctll::anything, line_comment>;
	static constexpr auto rule(comment, star) -> ctll::push<ctll::anything, block_comment>;

	static constexpr auto rule(line_comment, line_comment_chars) -> ctll::push<ctll::anything, line_comment>;
	static constexpr auto rule(line_comment, line_comment_chars2) -> ctll::epsilon;
	static constexpr auto rule(line_comment, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(block_comment, block_comment_chars) -> ctll::push<ctll::anything, block_comment>;
	static constexpr auto rule(block_comment, star) -> ctll::push<ctll::anything, block_comment_star>;

	static constexpr auto rule(block_comment_star, slash) -> ctll::push<ctll::anything>;
	static constexpr auto rule(block_comment_star, star) -> ctll::push<ctll::anything, block_comment_star>;
	static constexpr auto rule(block_comment_star, block_comment_chars) -> ctll::push<ctll::anything, block_comment>;

	static constexpr auto rule(value, lbrace) -> ctll::push<ctll::anything, begin_object, ws, object_content>;
	static constexpr auto rule(value, lbracket) -> ctll::push<ctll::anything, begin_array, ws, array_content>;
	static constexpr auto rule(value, quote) -> ctll::push<ctll::anything, begin_string, dq_content>;
	static constexpr auto rule(value, squote) -> ctll::push<ctll::anything, begin_string, sq_content>;
	static constexpr auto rule(value, plus__minus__dot__digit__I__N) -> ctll::push<number>;
	static constexpr auto rule(value, t) -> ctll::push<ctll::anything, r, u, e, push_true>;
	static constexpr auto rule(value, f) -> ctll::push<ctll::anything, a, l, s, e, push_false>;
	static constexpr auto rule(value, n) -> ctll::push<ctll::anything, u, l, l, push_null>;

	static constexpr auto rule(object_content, rbrace) -> ctll::push<ctll::anything, end_object>;
	static constexpr auto rule(object_content, doublequote__id_start__quote) -> ctll::push<member, object_tail>;

	static constexpr auto rule(object_tail, rbrace) -> ctll::push<ctll::anything, end_object>;
	static constexpr auto rule(object_tail, comma) -> ctll::push<ctll::anything, ws, object_after_comma>;

	static constexpr auto rule(object_after_comma, rbrace) -> ctll::push<ctll::anything, end_object>;
	static constexpr auto rule(object_after_comma, doublequote__id_start__quote) -> ctll::push<member, object_tail>;

	static constexpr auto rule(member, quote) -> ctll::push<ctll::anything, begin_string, dq_content, make_key, ws, colon, ws, value, make_member, ws>;
	static constexpr auto rule(member, squote) -> ctll::push<ctll::anything, begin_string, sq_content, make_key, ws, colon, ws, value, make_member, ws>;
	static constexpr auto rule(member, id_start) -> ctll::push<ctll::anything, begin_string, push_string_char, identifier_tail, make_key, ws, colon, ws, value, make_member, ws>;

	static constexpr auto rule(identifier_tail, id_continue) -> ctll::push<ctll::anything, push_string_char, identifier_tail>;
	static constexpr auto rule(identifier_tail, ws_char__slash__colon__Â__â__ï) -> ctll::epsilon;

	static constexpr auto rule(array_content, rbracket) -> ctll::push<ctll::anything, end_array>;
	static constexpr auto rule(array_content, set_3) -> ctll::push<value, ws, array_tail>;

	static constexpr auto rule(array_tail, rbracket) -> ctll::push<ctll::anything, end_array>;
	static constexpr auto rule(array_tail, comma) -> ctll::push<ctll::anything, ws, array_after_comma>;

	static constexpr auto rule(array_after_comma, rbracket) -> ctll::push<ctll::anything, end_array>;
	static constexpr auto rule(array_after_comma, set_3) -> ctll::push<value, ws, array_tail>;

	static constexpr auto rule(dq_content, quote) -> ctll::push<ctll::anything, end_string>;
	static constexpr auto rule(dq_content, dq_chars) -> ctll::push<ctll::anything, push_string_char, dq_content>;
	static constexpr auto rule(dq_content, backslash) -> ctll::push<ctll::anything, escape, dq_content>;

	static constexpr auto rule(sq_content, squote) -> ctll::push<ctll::anything, end_string>;
	static constexpr auto rule(sq_content, sq_chars) -> ctll::push<ctll::anything, push_string_char, sq_content>;
	static constexpr auto rule(sq_content, backslash) -> ctll::push<ctll::anything, escape, sq_content>;

	static constexpr auto rule(escape, escapable__d0) -> ctll::push<ctll::anything, push_escaped_char>;
	static constexpr auto rule(escape, x_char) -> ctll::push<ctll::anything, begin_hex, hexdig, push_hex, hexdig, push_hex, end_hex>;
	static constexpr auto rule(escape, u) -> ctll::push<ctll::anything, begin_hex, hexdig, push_hex, hexdig, push_hex, hexdig, push_hex, hexdig, push_hex, end_hex>;
	static constexpr auto rule(escape, x0a) -> ctll::push<ctll::anything>;
	static constexpr auto rule(escape, x0d) -> ctll::push<ctll::anything, continuation_lf>;
	static constexpr auto rule(escape, â) -> ctll::push<ctll::anything, x80, ls_ps_third>;
	static constexpr auto rule(escape, self_escape_chars) -> ctll::push<ctll::anything, push_string_char>;

	static constexpr auto rule(continuation_lf, x0a) -> ctll::push<ctll::anything, line_continuation>;
	static constexpr auto rule(continuation_lf, doublequote__quote__backslash) -> ctll::epsilon;
	static constexpr auto rule(continuation_lf, dq_chars) -> ctll::epsilon;
	static constexpr auto rule(continuation_lf, sq_chars) -> ctll::epsilon;

	static constexpr auto rule(number, minus) -> ctll::push<ctll::anything, begin_number, push_number_char, signed_numeric>;
	static constexpr auto rule(number, plus) -> ctll::push<ctll::anything, begin_number, signed_numeric>;
	static constexpr auto rule(number, zero) -> ctll::push<ctll::anything, begin_number, push_number_char, after_zero>;
	static constexpr auto rule(number, onenine) -> ctll::push<ctll::anything, begin_number, push_number_char, int_tail>;
	static constexpr auto rule(number, dot) -> ctll::push<ctll::anything, begin_number, push_number_char, leading_frac>;
	static constexpr auto rule(number, I) -> ctll::push<ctll::anything, begin_number, n, f, i, n, i, t, y, finish_infinity>;
	static constexpr auto rule(number, N) -> ctll::push<ctll::anything, begin_number, a, N, finish_nan>;

	static constexpr auto rule(signed_numeric, zero) -> ctll::push<ctll::anything, push_number_char, after_zero>;
	static constexpr auto rule(signed_numeric, onenine) -> ctll::push<ctll::anything, push_number_char, int_tail>;
	static constexpr auto rule(signed_numeric, dot) -> ctll::push<ctll::anything, push_number_char, leading_frac>;
	static constexpr auto rule(signed_numeric, I) -> ctll::push<ctll::anything, n, f, i, n, i, t, y, finish_infinity>;
	static constexpr auto rule(signed_numeric, N) -> ctll::push<ctll::anything, a, N, finish_nan>;

	static constexpr auto rule(after_zero, x_char) -> ctll::push<ctll::anything, push_number_char, hexdig, push_number_char, hex_tail>;
	static constexpr auto rule(after_zero, ws_char__comma__dot__slash__e_char__sclose__cclose__Â__â__ï) -> ctll::push<frac_part>;
	static constexpr auto rule(after_zero, ctll::epsilon) -> ctll::push<frac_part>;

	static constexpr auto rule(hex_tail, hexdig) -> ctll::push<ctll::anything, push_number_char, hex_tail>;
	static constexpr auto rule(hex_tail, ws_char__comma__slash__sclose__cclose__Â__â__ï) -> ctll::epsilon;
	static constexpr auto rule(hex_tail, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(int_tail, digit) -> ctll::push<ctll::anything, push_number_char, int_tail>;
	static constexpr auto rule(int_tail, ws_char__comma__dot__slash__e_char__sclose__cclose__Â__â__ï) -> ctll::push<frac_part>;
	static constexpr auto rule(int_tail, ctll::epsilon) -> ctll::push<frac_part>;

	static constexpr auto rule(leading_frac, digit) -> ctll::push<ctll::anything, push_number_char, frac_tail>;

	static constexpr auto rule(frac_part, dot) -> ctll::push<ctll::anything, push_number_char, frac_tail>;
	static constexpr auto rule(frac_part, ws_char__comma__slash__e_char__sclose__cclose__Â__â__ï) -> ctll::push<exp_part>;
	static constexpr auto rule(frac_part, ctll::epsilon) -> ctll::push<exp_part>;

	static constexpr auto rule(frac_tail, digit) -> ctll::push<ctll::anything, push_number_char, frac_tail>;
	static constexpr auto rule(frac_tail, ws_char__comma__slash__e_char__sclose__cclose__Â__â__ï) -> ctll::push<exp_part>;
	static constexpr auto rule(frac_tail, ctll::epsilon) -> ctll::push<exp_part>;

	static constexpr auto rule(exp_part, e_char) -> ctll::push<ctll::anything, push_number_char, exp_sign>;
	static constexpr auto rule(exp_part, ws_char__comma__slash__sclose__cclose__Â__â__ï) -> ctll::epsilon;
	static constexpr auto rule(exp_part, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(exp_sign, plus__minus) -> ctll::push<ctll::anything, push_number_char, exp_first>;
	static constexpr auto rule(exp_sign, digit) -> ctll::push<ctll::anything, push_number_char, exp_tail>;

	static constexpr auto rule(exp_first, digit) -> ctll::push<ctll::anything, push_number_char, exp_tail>;

	static constexpr auto rule(exp_tail, digit) -> ctll::push<ctll::anything, push_number_char, exp_tail>;
	static constexpr auto rule(exp_tail, ws_char__comma__slash__sclose__cclose__Â__â__ï) -> ctll::epsilon;
	static constexpr auto rule(exp_tail, ctll::epsilon) -> ctll::epsilon;

};

}

#endif //CTJSON5__JSON5__HPP
