#ifndef CTJSON__JSON__HPP
#define CTJSON__JSON__HPP

// THIS FILE WAS GENERATED BY TABLEWRIGHT TOOL, DO NOT MODIFY THIS FILE

#include "../ctll/grammars.hpp"

namespace ctjson {

struct json {

	// NONTERMINALS:
	struct array_content {};
	struct array_tail {};
	struct document {}; using _start = document;
	struct escape {};
	struct exp_first {};
	struct exp_part {};
	struct exp_sign {};
	struct exp_tail {};
	struct frac_part {};
	struct frac_tail {};
	struct int_start {};
	struct int_tail {};
	struct member {};
	struct number {};
	struct object_content {};
	struct object_tail {};
	struct string_content {};
	struct value {};
	struct ws {};

	// 'action' types:
	struct begin_array: ctll::action {};
	struct begin_hex: ctll::action {};
	struct begin_number: ctll::action {};
	struct begin_object: ctll::action {};
	struct begin_string: ctll::action {};
	struct end_array: ctll::action {};
	struct end_hex: ctll::action {};
	struct end_object: ctll::action {};
	struct end_string: ctll::action {};
	struct make_key: ctll::action {};
	struct make_member: ctll::action {};
	struct push_escaped_char: ctll::action {};
	struct push_false: ctll::action {};
	struct push_hex: ctll::action {};
	struct push_null: ctll::action {};
	struct push_number_char: ctll::action {};
	struct push_string_char: ctll::action {};
	struct push_true: ctll::action {};

	// TERMINALS
	using ws_char__doublequote__minus__digit__sopen__f__n__t__copen = ctll::set<'\x09','\x0A','\x0D',' ','\"','-','0','1','2','3','4','5','6','7','8','9','[','f','n','t','\x7B'>;
	using ws_char = ctll::set<'\x09','\x0A','\x0D',' '>;
	using set_1 = ctll::set<'\"',',','-','0','1','2','3','4','5','6','7','8','9',':','[',']','f','n','t','\x7B','\x7D'>;
	using r = ctll::term<'r'>;
	using u = ctll::term<'u'>;
	using e = ctll::term<'e'>;
	using a = ctll::term<'a'>;
	using l = ctll::term<'l'>;
	using s = ctll::term<'s'>;
	using lbrace = ctll::term<'\x7B'>;
	using lbracket = ctll::term<'['>;
	using quote = ctll::term<'\"'>;
	using minus__digit = ctll::set<'-','0','1','2','3','4','5','6','7','8','9'>;
	using t = ctll::term<'t'>;
	using f = ctll::term<'f'>;
	using n = ctll::term<'n'>;
	using rbrace = ctll::term<'\x7D'>;
	using comma = ctll::term<','>;
	using colon = ctll::term<':'>;
	using rbracket = ctll::term<']'>;
	using doublequote__minus__digit__sopen__f__n__t__copen = ctll::set<'\"','-','0','1','2','3','4','5','6','7','8','9','[','f','n','t','\x7B'>;
	using string_chars = ctll::neg_set<'\x00','\x01','\x02','\x03','\x04','\x05','\x06','\x07','\x08','\x09','\x0A','\x0B','\x0C','\x0D','\x0E','\x0F','\x10','\x11','\x12','\x13','\x14','\x15','\x16','\x17','\x18','\x19','\x1A','\x1B','\x1C','\x1D','\x1E','\x1F','\"','\\'>;
	using backslash = ctll::term<'\\'>;
	using hexdig = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','a','b','c','d','e','f'>;
	using escapable = ctll::set<'\"','/','\\','b','f','n','r','t'>;
	using minus = ctll::term<'-'>;
	using zero = ctll::term<'0'>;
	using onenine = ctll::set<'1','2','3','4','5','6','7','8','9'>;
	using digit = ctll::set<'0','1','2','3','4','5','6','7','8','9'>;
	using ws_char__comma__dot__e_char__sclose__cclose = ctll::set<'\x09','\x0A','\x0D',' ',',','.','E',']','e','\x7D'>;
	using dot = ctll::term<'.'>;
	using ws_char__comma__e_char__sclose__cclose = ctll::set<'\x09','\x0A','\x0D',' ',',','E',']','e','\x7D'>;
	using e_char = ctll::set<'E','e'>;
	using ws_char__comma__sclose__cclose = ctll::set<'\x09','\x0A','\x0D',' ',',',']','\x7D'>;
	using plus__minus = ctll::set<'+','-'>;

	// (q)LL1 function:
	static constexpr auto rule(document, ws_char__doublequote__minus__digit__sopen__f__n__t__copen) -> ctll::push<ws, value, ws>;

	static constexpr auto rule(ws, ws_char) -> ctll::push<ctll::anything, ws>;
	static constexpr auto rule(ws, set_1) -> ctll::epsilon;
	static constexpr auto rule(ws, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(value, lbrace) -> ctll::push<ctll::anything, begin_object, ws, object_content>;
	static constexpr auto rule(value, lbracket) -> ctll::push<ctll::anything, begin_array, ws, array_content>;
	static constexpr auto rule(value, quote) -> ctll::push<ctll::anything, begin_string, string_content>;
	static constexpr auto rule(value, minus__digit) -> ctll::push<number>;
	static constexpr auto rule(value, t) -> ctll::push<ctll::anything, r, u, e, push_true>;
	static constexpr auto rule(value, f) -> ctll::push<ctll::anything, a, l, s, e, push_false>;
	static constexpr auto rule(value, n) -> ctll::push<ctll::anything, u, l, l, push_null>;

	static constexpr auto rule(object_content, rbrace) -> ctll::push<ctll::anything, end_object>;
	static constexpr auto rule(object_content, quote) -> ctll::push<member, object_tail>;

	static constexpr auto rule(object_tail, rbrace) -> ctll::push<ctll::anything, end_object>;
	static constexpr auto rule(object_tail, comma) -> ctll::push<ctll::anything, ws, member, object_tail>;

	static constexpr auto rule(member, quote) -> ctll::push<ctll::anything, begin_string, string_content, make_key, ws, colon, ws, value, make_member, ws>;

	static constexpr auto rule(array_content, rbracket) -> ctll::push<ctll::anything, end_array>;
	static constexpr auto rule(array_content, doublequote__minus__digit__sopen__f__n__t__copen) -> ctll::push<value, ws, array_tail>;

	static constexpr auto rule(array_tail, rbracket) -> ctll::push<ctll::anything, end_array>;
	static constexpr auto rule(array_tail, comma) -> ctll::push<ctll::anything, ws, value, ws, array_tail>;

	static constexpr auto rule(string_content, quote) -> ctll::push<ctll::anything, end_string>;
	static constexpr auto rule(string_content, string_chars) -> ctll::push<ctll::anything, push_string_char, string_content>;
	static constexpr auto rule(string_content, backslash) -> ctll::push<ctll::anything, escape, string_content>;

	static constexpr auto rule(escape, escapable) -> ctll::push<ctll::anything, push_escaped_char>;
	static constexpr auto rule(escape, u) -> ctll::push<ctll::anything, begin_hex, hexdig, push_hex, hexdig, push_hex, hexdig, push_hex, hexdig, push_hex, end_hex>;

	static constexpr auto rule(number, minus) -> ctll::push<ctll::anything, begin_number, push_number_char, int_start>;
	static constexpr auto rule(number, zero) -> ctll::push<ctll::anything, begin_number, push_number_char, frac_part>;
	static constexpr auto rule(number, onenine) -> ctll::push<ctll::anything, begin_number, push_number_char, int_tail>;

	static constexpr auto rule(int_start, zero) -> ctll::push<ctll::anything, push_number_char, frac_part>;
	static constexpr auto rule(int_start, onenine) -> ctll::push<ctll::anything, push_number_char, int_tail>;

	static constexpr auto rule(int_tail, digit) -> ctll::push<ctll::anything, push_number_char, int_tail>;
	static constexpr auto rule(int_tail, ws_char__comma__dot__e_char__sclose__cclose) -> ctll::push<frac_part>;
	static constexpr auto rule(int_tail, ctll::epsilon) -> ctll::push<frac_part>;

	static constexpr auto rule(frac_part, dot) -> ctll::push<ctll::anything, push_number_char, digit, push_number_char, frac_tail>;
	static constexpr auto rule(frac_part, ws_char__comma__e_char__sclose__cclose) -> ctll::push<exp_part>;
	static constexpr auto rule(frac_part, ctll::epsilon) -> ctll::push<exp_part>;

	static constexpr auto rule(frac_tail, digit) -> ctll::push<ctll::anything, push_number_char, frac_tail>;
	static constexpr auto rule(frac_tail, ws_char__comma__e_char__sclose__cclose) -> ctll::push<exp_part>;
	static constexpr auto rule(frac_tail, ctll::epsilon) -> ctll::push<exp_part>;

	static constexpr auto rule(exp_part, e_char) -> ctll::push<ctll::anything, push_number_char, exp_sign>;
	static constexpr auto rule(exp_part, ws_char__comma__sclose__cclose) -> ctll::epsilon;
	static constexpr auto rule(exp_part, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(exp_sign, plus__minus) -> ctll::push<ctll::anything, push_number_char, exp_first>;
	static constexpr auto rule(exp_sign, digit) -> ctll::push<ctll::anything, push_number_char, exp_tail>;

	static constexpr auto rule(exp_first, digit) -> ctll::push<ctll::anything, push_number_char, exp_tail>;

	static constexpr auto rule(exp_tail, digit) -> ctll::push<ctll::anything, push_number_char, exp_tail>;
	static constexpr auto rule(exp_tail, ws_char__comma__sclose__cclose) -> ctll::epsilon;
	static constexpr auto rule(exp_tail, ctll::epsilon) -> ctll::epsilon;

};

}

#endif //CTJSON__JSON__HPP
